definitions:
  domain.Users:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
  handler.Response:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/users:
    get:
      description: Get all users
      operationId: FindAll
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Response'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Get all users
      tags:
      - users
    post:
      description: register user
      operationId: register
      parameters:
      - description: user signup
        in: body
        name: RegisterUser
        required: true
        schema:
          $ref: '#/definitions/domain.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Response'
            type: array
      summary: Get all users
      tags:
      - users
swagger: "2.0"
